### ISSUE TITLE
Could you integrate TOC ?

### ISSUE THREAD

**Issue by STnetwork** [chrismwilliams/gatsby-theme-cactus#5]
Hi,

Could you integrate a TOC ? Like the original theme ?

Thanks in advance

**Comment by chrismwilliams** [comment]
Thank for the suggestion, forgive me but I'm not quite sure what you mean by TOC? If you could provide a link or example I can take a look

**Comment by STnetwork** [comment]
Thanks for your answer, when I'm talking about TOC is like this in my screen : 

![Screenshot 2020-05-23 at 02 26 15](https://user-images.githubusercontent.com/26366663/82717524-e809a980-9c9c-11ea-9b7a-357fb1647bb3.png)

**Comment by chrismwilliams** [comment]
Ah gotcha! It seems the Hexo framework has it built-in. A quick search revealed a couple that could do the job, [minimap-react](https://github.com/UpForce-Tech/minimap-react) & [react-minimap](https://github.com/demux/react-minimap), but they'd need to be tested. I can certainly take a look and thanks again for the suggestion!

**Comment by chrismwilliams** [comment]
Actually, scratch that. The posts are mdx, so yes it should be fine

**Comment by STnetwork** [comment]
thanks for your work !

**Comment by chrismwilliams** [comment]
No problem, and thanks again for the suggestion!
